#!/usr/bin/env bash
# Turns the compiled SPIR-V cache into a C++ header the engine links into itself.
#
# This is what makes a VAE app standalone. Reading the modules off disk at startup meant every
# binary built against the engine had to find the engine's checkout at *run* time — the `.vaeroot`
# walk-up — so an exported app moved to another machine came up with no pipelines and a blank
# window. 17 KB of SPIR-V in .rodata costs nothing and removes the whole class of failure.
#
# Reads the cache rather than compiling it, so `make` needs no glslc: shaders are compiled by
# scripts/CompileShaders.sh, which calls this at the end. Byte arrays rather than uint32 words
# because the loader memcpy's them, which is byte-order-agnostic exactly as reading the file was.
#
#   ./scripts/EmbedShaders.sh PATH   writes the header, and only rewrites it when it changed
set -euo pipefail

HERE="$(cd "$(dirname "$0")/.." && pwd)"
OUT=${1:-$HERE/VAE/vendor-generated/vae/Shaders.gen.h}
CACHE=$HERE/VAE/assets/shaders/cache

shopt -s nullglob
modules=("$CACHE"/*.spv)
if [ ${#modules[@]} -eq 0 ]; then
    echo "EmbedShaders.sh: no SPIR-V in $CACHE — run scripts/CompileShaders.sh first" >&2
    exit 1
fi

# A C++ identifier per module: quad.vert -> kQuad_vert.
symbol() {
    local base
    base=$(basename "$1" .spv)
    printf 'k%s' "$(printf '%s' "$base" | sed -e 's/[^A-Za-z0-9]/_/g' -e 's/^\(.\)/\U\1/')"
}

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

{
    echo "// Generated by scripts/EmbedShaders.sh — do not edit, and do not commit."
    echo "#pragma once"
    echo
    echo "#include <cstddef>"
    echo "#include <cstdint>"
    echo "#include <string_view>"
    echo
    echo "namespace vae::gpu::embedded {"
    echo
    for spv in "${modules[@]}"; do
        sym=$(symbol "$spv")
        echo "    // $(basename "$spv" .spv) — $(wc -c < "$spv") bytes"
        echo "    inline constexpr std::uint8_t ${sym}[] = {"
        od -An -v -tu1 "$spv" | awk '{ line = "       "; for (i = 1; i <= NF; ++i) line = line " " $i ","; print line }'
        echo "    };"
        echo
    done
    echo "    struct Module { std::string_view name; const std::uint8_t* bytes; std::size_t size; };"
    echo
    echo "    inline constexpr Module kModules[] = {"
    for spv in "${modules[@]}"; do
        sym=$(symbol "$spv")
        printf '        { "%s", %s, sizeof %s },\n' "$(basename "$spv" .spv)" "$sym" "$sym"
    done
    echo "    };"
    echo
    echo "}"
} > "$tmp"

# Only when it changed: this runs as a prebuild step, and rewriting it every build would
# recompile the renderer every build.
mkdir -p "$(dirname "$OUT")"
if [ -f "$OUT" ] && cmp -s "$tmp" "$OUT"; then exit 0; fi
cp "$tmp" "$OUT"
chmod 644 "$OUT"   # mktemp makes it 0600, and a generated header is not a secret
