#!/usr/bin/env bash
# The one place a VAE version number comes from.
#
# Two numbers, both out of git, nothing declared in a file — a version in a file is a version
# somebody forgets to edit. Same scheme mem-manager runs, which is KernelSU's:
#
#   code   10000 + N   N = commits on HEAD. Monotonic, never hand-maintained. Says *which* build
#                      something is, and nothing about whether it is compatible with anything.
#   name   git describe --tags --always --dirty
#                      "v1.0" exactly at the tag, "v1.0-12-gabc1234" twelve commits past it, the
#                      bare hash before the first tag.
#
# **Releasing is tagging.** `git tag v1.1` is the whole ceremony; every build afterwards says v1.1
# without anything else being edited.
#
# Compatibility is a different question and lives in its own hand-bumped constants, none of which
# this script touches: Serializer::kFormatVersion (documents), VAE_SCRIPT_ABI_VERSION (the script
# ABI) and kLibraryVersion (the widget catalog).
#
#   ./scripts/version.sh          -> "10012 v0.1-3-gabc1234"
#   ./scripts/version.sh code     -> "10012"
#   ./scripts/version.sh name     -> "v0.1-3-gabc1234"
#   ./scripts/version.sh header PATH   writes a C++ header, and only rewrites it when it changed
set -euo pipefail

HERE="$(cd "$(dirname "$0")/.." && pwd)"

# 0 and "unknown", not a plausible-looking number, when git cannot answer. KernelSU's fallback is a
# hardcoded 16, which reads like a real version and produced mismatch reports nobody could
# interpret. 0 means "this build does not know what it is", and every consumer prints it as unknown
# rather than comparing it.
code=0
name="unknown"

if git -C "$HERE" rev-parse --git-dir >/dev/null 2>&1; then
    # A shallow clone counts wrong and would quietly produce a *lower* number than the build before
    # it. Say so rather than emit one; a CI checkout wants fetch-depth: 0.
    if [ -f "$(git -C "$HERE" rev-parse --git-dir)/shallow" ]; then
        echo "version.sh: shallow clone — 'git fetch --unshallow' for a real build number" >&2
    else
        commits=$(git -C "$HERE" rev-list --count HEAD 2>/dev/null || echo 0)
        [ "$commits" -gt 0 ] && code=$((10000 + commits))
    fi
    name=$(git -C "$HERE" describe --tags --always --dirty 2>/dev/null || echo unknown)
fi

case "${1:-both}" in
    code) echo "$code" ;;
    name) echo "$name" ;;
    both) echo "$code $name" ;;
    header)
        out="${2:?usage: $0 header <path>}"
        mkdir -p "$(dirname "$out")"
        printf '// Generated by scripts/version.sh. Do not edit, do not commit.\n#pragma once\n#define VAE_VERSION_CODE %su\n#define VAE_VERSION_NAME "%s"\n' \
               "$code" "$name" > "$out.tmp"
        # Only replace it when it actually changed: every build would otherwise recompile the world
        # because a header with a new timestamp is a header everything depends on.
        if [ -f "$out" ] && cmp -s "$out" "$out.tmp"; then rm -f "$out.tmp"; else mv "$out.tmp" "$out"; fi
        ;;
    *) echo "usage: $0 [code|name|both|header <path>]" >&2; exit 2 ;;
esac
